linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - internal/middlewares/.*\.go

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck