package controllers

import (
	"dz-jobs-api/data/request"
	"dz-jobs-api/data/response"
	"dz-jobs-api/internal/services"
	"dz-jobs-api/pkg/helpers"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"

	// Swagger imports
	// This will be generated by swag
)



// AuthenticationController godoc
// @Description Handles authentication-related operations
type AuthenticationController struct {
	AuthenticationService services.AuthenticationService
}

// NewAuthenticationController creates a new AuthenticationController
func NewAuthenticationController(service services.AuthenticationService) *AuthenticationController {
	return &AuthenticationController{AuthenticationService: service}
}

// Login godoc
// @Summary User Login
// @Description Authenticate user and generate access token
// @Tags Authentication
// @Accept json
// @Produce json
// @Param loginRequest body request.LoginRequest true "Login Credentials"
// @Success 200 {object} response.Response{data=response.LoginResponse} "Successfully logged in"
// @Failure 400 {object} response.Response "Invalid username or password"
// @Router /auth/login [post]
func (controller *AuthenticationController) Login(ctx *gin.Context) {
	loginRequest := request.LoginRequest{}
	err := ctx.ShouldBindJSON(&loginRequest)
	helpers.ErrorPanic(err)

	token, err_token := controller.AuthenticationService.Login(loginRequest)
	fmt.Println(err_token)
	if err_token != nil {
		webResponse := response.Response{
			Code:    http.StatusBadRequest,
			Status:  "Bad Request",
			Message: "Invalid username or password",
		}
		ctx.JSON(http.StatusBadRequest, webResponse)
		return
	}

	resp := response.LoginResponse{
		TokenType: "Bearer",
		Token:     token,
	}

	webResponse := response.Response{
		Code:    200,
		Status:  "Ok",
		Message: "Successfully log in!",
		Data:    resp,
	}

	ctx.JSON(http.StatusOK, webResponse)
}

// Register godoc
// @Summary User Registration
// @Description Register a new user in the system
// @Tags Authentication
// @Accept json
// @Produce json
// @Param userRequest body request.CreateUsersRequest true "User Registration Details"
// @Success 200 {object} response.Response "Successfully created user"
// @Failure 400 {object} response.Response "Invalid registration details"
// @Router /auth/register [post]
func (controller *AuthenticationController) Register(ctx *gin.Context) {
	createUsersRequest := request.CreateUsersRequest{}
	err := ctx.ShouldBindJSON(&createUsersRequest)
	helpers.ErrorPanic(err)

	controller.AuthenticationService.Register(createUsersRequest)

	webResponse := response.Response{
		Code:    200,
		Status:  "Ok",
		Message: "Successfully created user!",
		Data:    nil,
	}

	ctx.JSON(http.StatusOK, webResponse)
}
